### ISSUE TITLE
SPYT: Can't combine "recursiveFileLookup" with "basePath"

### ISSUE THREAD

**Issue by Hattonuri** [ytsaurus/ytsaurus#158]
I am trying to do
`df = spark.read.option("recursiveFileLookup", "false").option("basePath", "//ProcessedData/test/").yt('//ProcessedData/test/lol=kek')`
And get
`Py4JJavaError: An error occurred while calling o310.load.
: org.apache.hadoop.fs.UnsupportedFileSystemException: No FileSystem for scheme "null"
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3443)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
	at org.apache.spark.sql.execution.datasources.PartitioningAwareFileIndex.basePaths(PartitioningAwareFileIndex.scala:227)
	at org.apache.spark.sql.execution.datasources.PartitioningAwareFileIndex.inferPartitioning(PartitioningAwareFileIndex.scala:161)
	at org.apache.spark.sql.v2.YtInMemoryFileIndex.partitionSpec(YtInMemoryFileIndex.scala:54)
	at org.apache.spark.sql.v2.YtInMemoryFileIndex.allFiles(YtInMemoryFileIndex.scala:146)
	at org.apache.spark.sql.execution.datasources.v2.FileTable.$anonfun$dataSchema$4(FileTable.scala:71)
	at scala.Option.orElse(Option.scala:447)
	at org.apache.spark.sql.execution.datasources.v2.FileTable.dataSchema$lzycompute(FileTable.scala:71)
	at org.apache.spark.sql.execution.datasources.v2.FileTable.dataSchema(FileTable.scala:65)
	at org.apache.spark.sql.execution.datasources.v2.FileTable.schema$lzycompute(FileTable.scala:85)
	at org.apache.spark.sql.execution.datasources.v2.FileTable.schema(FileTable.scala:83)
	at org.apache.spark.sql.execution.datasources.v2.FileDataSourceV2.inferSchema(FileDataSourceV2.scala:94)
	at org.apache.spark.sql.execution.datasources.v2.FileDataSourceV2.inferSchema$(FileDataSourceV2.scala:92)
	at org.apache.spark.sql.v2.YtDataSourceV2.inferSchema(YtDataSourceV2.scala:14)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Utils$.getTableFromProvider(DataSourceV2Utils.scala:81)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$1(DataFrameReader.scala:233)
	at scala.Option.map(Option.scala:230)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)`

**Comment by Alexvsalexvsalex** [comment]
`.yt(path)` is just syntax sugar for `.format("yt").load("ytTable:/" + path)`. So real full path has prefix `ytTable`.
When you use "basePath" there is no sugar and you must specify full path.
So correct way:
```python
df = spark.read.option("recursiveFileLookup", "false").option("basePath", "ytTable:///ProcessedData/test/").yt('//ProcessedData/test/lol=kek')
```
