### ISSUE TITLE
Operations with typed jobs ignore schema from input paths

### ISSUE THREAD

**Issue by chegoryu** [ytsaurus/ytsaurus#212]
The following code creates output table without sorted part:

```python
from typing import (
    Iterable,
)

from yt.wrapper import (
    YtClient,
    TablePath,
    TypedJob,
    with_context as yt_with_context,
)
from yt.wrapper.default_config import get_config_from_env

from yt.wrapper.schema import (
    Context,
    TableSchema,
    yt_dataclass,
)


@yt_dataclass
class InputRow:
    name: str


@yt_dataclass
class OutputRow:
    index: int
    name: str


@yt_with_context
class Mapper(TypedJob):
    def __call__(self, row: InputRow, context: Context) -> Iterable[OutputRow]:
        yield OutputRow(context.get_row_index(), row.name)


if __name__ == '__main__':
    client = YtClient(config=get_config_from_env())

    client.remove("//tmp/echunaev/input", force=True)
    client.write_table_structured("//tmp/echunaev/input", InputRow, [InputRow(name="a"), InputRow(name="b")])

    client.remove("//tmp/echunaev/output", force=True)
    client.run_map(
        Mapper(),
        "//tmp/echunaev/input",
        TablePath("//tmp/echunaev/output", schema=TableSchema.from_row_type(OutputRow).build_schema_sorted_by("index")),
        ordered=True,
    )
```

<img width="2001" alt="Screenshot 2023-12-03 at 20 37 09" src="https://github.com/ytsaurus/ytsaurus/assets/29466571/58bc59eb-af4a-4757-86f6-6163ec75a268">

And after adding `OtherColumns` to `OutputRow` it even fails to prepare operation:

```python
@yt_dataclass
class OutputRow:
    index: int
    name: str
    other_columns: OtherColumns

```

Error:

```python
Traceback (most recent call last):
  File "/home/echunaev/repro.py", line 52, in <module>
    client.run_map(
  File "/usr/twix/python3.11/lib/python3.11/site-packages/yt/wrapper/client_impl.py", line 2045, in run_map
    return client_api.run_map(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/twix/python3.11/lib/python3.11/site-packages/yt/wrapper/run_operation_commands.py", line 295, in run_map
    return run_operation(spec_builder, sync=sync, enable_optimizations=True, client=client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<decorator-gen-8>", line 2, in run_operation
  File "/usr/twix/python3.11/lib/python3.11/site-packages/yt/wrapper/common.py", line 421, in forbidden_inside_job
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/twix/python3.11/lib/python3.11/site-packages/yt/wrapper/run_operation_commands.py", line 607, in run_operation
    spec = spec_builder.build(client=client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/twix/python3.11/lib/python3.11/site-packages/yt/wrapper/spec_builders.py", line 1214, in build
    spec = self._do_build(client)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/twix/python3.11/lib/python3.11/site-packages/yt/wrapper/spec_builders.py", line 1534, in _do_build
    spec = self._build_simple_user_job_spec(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/twix/python3.11/lib/python3.11/site-packages/yt/wrapper/spec_builders.py", line 1059, in _build_simple_user_job_spec
    spec, input_tables, output_tables = self._build_user_job_spec(
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/twix/python3.11/lib/python3.11/site-packages/yt/wrapper/spec_builders.py", line 1083, in _build_user_job_spec
    spec[job_type], input_tables, output_tables = job_spec_builder.build(
                                                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/twix/python3.11/lib/python3.11/site-packages/yt/wrapper/spec_builders.py", line 769, in build
    input_format, output_format, input_tables, output_tables = run_operation_preparation(
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/twix/python3.11/lib/python3.11/site-packages/yt/wrapper/prepare_operation.py", line 344, in run_operation_preparation
    preparer._finish()
  File "/usr/twix/python3.11/lib/python3.11/site-packages/yt/wrapper/prepare_operation.py", line 245, in _finish
    self._output_schemas[index] = TableSchema.from_row_type(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/twix/python3.11/lib/python3.11/site-packages/yt/wrapper/schema/table_schema.py", line 135, in from_row_type
    raise YtError('Cannot infer strict schema from yt_dataclass "{}" with field marked with "OtherColumns"'
yt.common.YtError: Cannot infer strict schema from yt_dataclass "OutputRow" with field marked with "OtherColumns"

```

This bug is not critical because it is still possible to create output table with correct schema before operation and it will work fine.

**Comment by chegoryu** [comment]
I believe this should work because it now works for untyped jobs:

https://github.com/ytsaurus/ytsaurus/blob/2d463a24c4412cae3d0fa4c2a3a09eb09a344183/yt/python/yt/wrapper/tests/test_operations.py#L236-L245
