### ISSUE TITLE
Error in query tracker init job

### ISSUE THREAD

**Issue by gritukan** [ytsaurus/ytsaurus#349]
```
++ export YT_DRIVER_CONFIG_PATH=/config/client.yson
++ YT_DRIVER_CONFIG_PATH=/config/client.yson
+++ /usr/bin/ytserver-all --version
+++ head -c4
++ export YTSAURUS_VERSION=23.3
++ YTSAURUS_VERSION=23.3
++ [[ -f /usr/bin/init_query_tracker_state ]]
++ /usr/bin/init_query_tracker_state --force --latest --proxy http-proxies.gelfand.svc.cluster.local
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/yt/wrapper/spec_builder_helpers.py", line 7, in <module>
    import yt.packages.distro as distro
ModuleNotFoundError: No module named 'yt.packages.distro'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/init_query_tracker_state", line 3, in <module>
    from yt.wrapper import YtClient, config
  File "/usr/local/lib/python3.8/dist-packages/yt/wrapper/__init__.py", line 16, in <module>
    from .client_api import *  # noqa
  File "/usr/local/lib/python3.8/dist-packages/yt/wrapper/client_api.py", line 15, in <module>
    from .run_operation_commands import (  # noqa
  File "/usr/local/lib/python3.8/dist-packages/yt/wrapper/run_operation_commands.py", line 46, in <module>
    from .spec_builders import (ReduceSpecBuilder, MergeSpecBuilder, SortSpecBuilder,
  File "/usr/local/lib/python3.8/dist-packages/yt/wrapper/spec_builders.py", line 15, in <module>
    from .spec_builder_helpers import BaseLayerDetector
  File "/usr/local/lib/python3.8/dist-packages/yt/wrapper/spec_builder_helpers.py", line 10, in <module>
    import distro
ModuleNotFoundError: No module named 'distro'
```

**Comment by Krisha11** [comment]
Fixed starting from [this image](
https://hub.docker.com/layers/ytsaurus/query-tracker-nightly/dev-69506-b13ced1b471063b0466d36e28374925544ae58df-relwithdebinfo/images/sha256-01805459afad4d02427c15855e65c355da854535c800459f19c3c7c572150694?context=explore)
