### ISSUE TITLE
It is impossible to run tests from `yt/python/yt/wrapper/tests` in OS build due to missing sandbox resource mapping

### ISSUE THREAD

**Issue by chegoryu** [ytsaurus/ytsaurus#392]
When I tried to do so, I got:
```bash
$ ya make -A -F '*test_sort*' 
# <some build log>
Error: Unable to fetch resource {'uri': 'sbr:4804987727'}
Traceback (most recent call last):
  File "devtools/ya/yalibrary/runner/tasks/resource.py", line 74, in __call__
    path = self.fetch()
           ^^^^^^^^^^^^
  File "devtools/ya/yalibrary/runner/tasks/resource.py", line 124, in fetch
    self._fetch_resource_if_need(
  File "devtools/ya/yalibrary/fetcher/resource_fetcher.py", line 82, in fetch_resource_if_need
    downloader = _get_downloader(fetcher, parsed_uri, progress_callback, state, keep_directory_packed)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "devtools/ya/yalibrary/fetcher/resource_fetcher.py", line 127, in _get_downloader
    return _HttpDownloaderWithConfigMapping(parsed_uri.resource_id, default_resource_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "devtools/ya/yalibrary/fetcher/resource_fetcher.py", line 173, in __init__
    raise MissingResourceError("Resource mapping doesn't have required resource: {}".format(resource_id))
yalibrary.fetcher.resource_fetcher.MissingResourceError: Resource mapping doesn't have required resource: 4804987727
------- RESOURCE $(sbr:4804987727)
ERROR: Resource mapping doesn't have required resource: 4804987727
Number of suites skipped due to a failed build: 4, skipped by name: 8, by filter *test_sort*

Total 0 suites
Total 0 tests
SOME TESTS DIDN'T RUN DUE TO BUILD ERRORS
Failed
```

The reason is here:
https://github.com/ytsaurus/ytsaurus/blob/47b3eac23ca0d2f079749f2d5d6032933ba18031/yt/python/yt/wrapper/tests/ya.make#L94-L101

It will be nice to hide tests with this resource under something like `IF NOT OPENSOURCE`.

**Comment by savnadya** [comment]
It was fixed here: https://github.com/ytsaurus/ytsaurus/commit/ae6eeaf7376b5a130cd105035b92b6d7687e697d
