### ISSUE TITLE
bug(cli): ValueError when running yt run-job-shell command

### ISSUE THREAD

**Issue by nordikafiles** [ytsaurus/ytsaurus#41]
When attempting to run a job shell with the `yt` command, I encountered an error. 

The error occurred during the execution of the following command:

<code>$ yt run-job-shell ec771307-d3b685d-10384-7</code>

This command resulted in a `ValueError: kwargs can't be used if request is an HTTPRequest object` traceback, as shown here:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/yt/wrapper/cli_helpers.py", line 75, in run_main
    main_func()
  File "/usr/local/lib/python3.8/dist-packages/yt/cli/yt_binary.py", line 2703, in main_func
    args.func(**func_args)
  File "/usr/local/lib/python3.8/dist-packages/yt/wrapper/job_commands.py", line 66, in run_job_shell
    JobShell(job_id, shell_name=shell_name, interactive=True, timeout=timeout, client=client).run(command=command)
  File "/usr/local/lib/python3.8/dist-packages/yt/wrapper/job_shell.py", line 328, in run
    self._spawn_shell(command=command)
  File "/usr/local/lib/python3.8/dist-packages/yt/wrapper/job_shell.py", line 258, in _spawn_shell
    self.make_request("spawn", callback=self._on_spawn_response, term=os.environ["TERM"], command=command)
  File "/usr/local/lib/python3.8/dist-packages/yt/wrapper/job_shell.py", line 162, in make_request
    self.client.fetch(req, callback=callback)
  File "/usr/local/lib/python3.8/dist-packages/tornado/httpclient.py", line 289, in fetch
    raise ValueError(
ValueError: kwargs can't be used if request is an HTTPRequest object
```

This issue occurred while running YT wrapper version 0.13.1, confirmed with the command:

<code>$ yt --version</code>

Which returned:

```
Version: YT wrapper 0.13.1
```

**Comment by denvr** [comment]
As quick fix - try to downgrade `tornado` to version 5.x
