### ISSUE TITLE
RPC backend deadlock in multi-threaded environment

### ISSUE THREAD

**Issue by chegoryu** [ytsaurus/ytsaurus#493]
```python
from concurrent.futures import ThreadPoolExecutor, as_completed
from yt.wrapper import YtClient
from yt.wrapper.default_config import get_config_from_env
from yt.wrapper.ypath import TablePath


def test(id: int) -> int:
    cfg = get_config_from_env()
    cfg.update(
        {
            "backend": "rpc",
            "driver_address_resolver_config": {
                "enable_ipv4": True,
                "enable_ipv6": False,
            },
        }
    )
    client = YtClient(config=cfg)
    table_stream = client.read_table(
        TablePath("//tmp/echunaev/test_arrow", start_index=0, end_index=5),
        format="yson",
        raw=True,
    )
    table_stream.read()
    return id


def main():
    with ThreadPoolExecutor(max_workers=5) as executor:
        futures = [executor.submit(test, i) for i in range(5)]
        for future in as_completed(futures):
            print(f"OK {future.result()}")

    test(4)

main()
```

If backend type is `rpc` this code prints
```
OK 1
OK 2
OK 4
OK 0
OK 3
after thread pool check
```

And then hangs.

If backend type is `http` everything works fine.

Strace shows something like this:
```
stat("/home/echunaev/.yt/token", {st_mode=S_IFREG|0400, st_size=36, ...}) = 0
gettid()                                = 2653862
futex(0x20da38c, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=99998000}) = -1 ETIMEDOUT (Connection timed out)
gettid()                                = 2653862
gettid()                                = 2653862
futex(0x20da38c, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=100000000}) = -1 ETIMEDOUT (Connection timed out)
gettid()                                = 2653862
gettid()                                = 2653862
futex(0x20da38c, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=99999000}) = -1 ETIMEDOUT (Connection timed out)
gettid()                                = 2653862
gettid()                                = 2653862
futex(0x20da38c, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=100000000}) = -1 ETIMEDOUT (Connection timed out)
gettid()                                = 2653862
gettid()                                = 2653862
futex(0x20da38c, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=99999000}) = -1 ETIMEDOUT (Connection timed out)
gettid()                                = 2653862
gettid()                                = 2653862
futex(0x20da38c, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=100000000}) = -1 ETIMEDOUT (Connection timed out)
gettid()                                = 2653862
gettid()                                = 2653862
futex(0x20da38c, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=99999000}) = -1 ETIMEDOUT (Connection timed out)
gettid()                                = 2653862
gettid()                                = 2653862
futex(0x20da38c, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=99998000}) = -1 ETIMEDOUT (Connection timed out)
gettid()                                = 2653862
gettid()                                = 2653862
futex(0x20da38c, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=99998000}) = -1 ETIMEDOUT (Connection timed out)
```

It feels like finishing a thread and then creating another client results in a deadlock.

Gdb is not very useful here :(
```
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007f8322d9d20c in ?? () from /usr/twix/python3.11/lib/python3.11/site-packages/yt_driver_rpc_bindings/driver_rpc_lib.so
#2  0x00007f8322d8f596 in ?? () from /usr/twix/python3.11/lib/python3.11/site-packages/yt_driver_rpc_bindings/driver_rpc_lib.so
#3  0x00007f8322d8ecbb in ?? () from /usr/twix/python3.11/lib/python3.11/site-packages/yt_driver_rpc_bindings/driver_rpc_lib.so
#4  0x00007f832395e98d in ?? () from /usr/twix/python3.11/lib/python3.11/site-packages/yt_driver_rpc_bindings/driver_rpc_lib.so
#5  0x00007f8323def4f9 in ?? () from /usr/twix/python3.11/lib/python3.11/site-packages/yt_driver_rpc_bindings/driver_rpc_lib.so
#6  0x00007f8323df0c24 in ?? () from /usr/twix/python3.11/lib/python3.11/site-packages/yt_driver_rpc_bindings/driver_rpc_lib.so
...
```

**Comment by chegoryu** [comment]
Well this is the intended behaviour :(
https://ytsaurus.tech/docs/en/api/python/userdoc#threadsafety
