### ISSUE TITLE
UI couldn’t be reached

### ISSUE THREAD

**Issue by dawsongzhao** [ytsaurus/ytsaurus#57]
I install ytsuarus as the follow instructions:
cd yt/docker/local
./run_local_cluster.sh

go to http://localhost:8001/ in chrome.
get the follow error:
UI couldn’t be reached
is there any tricks to fix it?

**Comment by savnadya** [comment]
Hello!
Can you please check if `docker exec -it yt.frontend curl http://yt.backend:80/version` works?
Probably there will be a timeout. It looks like something wrong with your containers. Is `yt.backend` container alive?

**Comment by dawsongzhao** [comment]
@savnadya Thanks for your reply.
This is my docker process after running `./run_local_cluster.sh`
docker ps -a
CONTAINER ID   IMAGE                COMMAND                  CREATED          STATUS          PORTS                    NAMES
39057c0d2135   ytsaurus/ui:stable   "/usr/local/bin/supe…"   22 seconds ago   Up 22 seconds   0.0.0.0:8001->80/tcp     yt.frontend
1712aa6d3302   postgres:14.2        "docker-entrypoint.s…"   2 months ago     Up 17 minutes   0.0.0.0:5432->5432/tcp   postgres

It seems yt.backend container do not running.

**Comment by dawsongzhao** [comment]
This is my computer info: 
<img width="215" alt="image" src="https://github.com/ytsaurus/ytsaurus/assets/7078308/a8bfa90c-2bc4-4d31-adc8-8f6963c99d81">

**Comment by dawsongzhao** [comment]
```
./run_local_cluster.sh
stable: Pulling from ytsaurus/local
Digest: sha256:bd031e033dd11b2e21ccddea837a17643750481ffe03a5d35fdeb295c82ce514
Status: Image is up to date for ytsaurus/local:stable
docker.io/ytsaurus/local:stable
stable: Pulling from ytsaurus/ui
Digest: sha256:d64b12f5532303eb8bbd531d3870c997f8671ce5da4bbbc44f0fda31b46a3b5d
Status: Image is up to date for ytsaurus/ui:stable
docker.io/ytsaurus/ui:stable
Creating network yt_local_cluster_network
f7e8ccc6f7cab20ddf1fc505fa58a98c0fc56d39b1b35564b44d5f8430b873f2

Congratulations! Local cluster is up and running. To use the cluster web interface, point your browser to http://localhost:8001. Or, if you prefer command-line tool 'yt', use it like this: 'yt --proxy localhost:8000 <command>'.

When you finish with the local interface,stop it by running a command:
	docker stop yt.backend yt.frontend
or
	./run_local_cluster.sh --stop
```  and i can't find any information about yt.backend

**Comment by savnadya** [comment]
`./run_local_cluster.sh` should run `yt.backend` too. So probably it was died soon after creating.
Can you please try to collect debug logs from this container while it is still alive?
You need to run `./run_local_cluster.sh --enable-debug-logs` and get all files from `yt.backend` container from `/tmp/<id>/logs`.

**Comment by dawsongzhao** [comment]
docker image list
REPOSITORY                                      TAG       IMAGE ID       CREATED          SIZE
querybook-dev                                   latest    cf733b26b78a   16 minutes ago   3.28GB
<none>                                          <none>    38e36174b555   24 hours ago     3.28GB
mysql                                           8.0       91b53e2624b4   7 days ago       565MB
caskdata/cdap-sandbox                           latest    b8c024514a99   10 days ago      3.72GB
qdrant/qdrant                                   latest    60763761a7a8   4 weeks ago      147MB
gcr.io/k8s-minikube/kicbase                     v0.0.39   67a4b1138d2d   2 months ago     1.05GB
ytsaurus/ui                                     stable    0f15676a2557   3 months ago     1.25GB
ytsaurus/local                                  stable    b6d0a20fc2f0   3 months ago     794MB
postgres                                        14.2      9dbc24674f25   13 months ago    376MB
docker.elastic.co/elasticsearch/elasticsearch   7.16.2    66c29cde15ce   18 months ago    646MB
redis                                           5.0.9     987b553c835f   2 years ago      98.3MB

**Comment by dawsongzhao** [comment]
```shell
docker image list
REPOSITORY                                      TAG       IMAGE ID       CREATED          SIZE
querybook-dev                                   latest    cf733b26b78a   16 minutes ago   3.28GB
<none>                                          <none>    38e36174b555   24 hours ago     3.28GB
mysql                                           8.0       91b53e2624b4   7 days ago       565MB
caskdata/cdap-sandbox                           latest    b8c024514a99   10 days ago      3.72GB
qdrant/qdrant                                   latest    60763761a7a8   4 weeks ago      147MB
gcr.io/k8s-minikube/kicbase                     v0.0.39   67a4b1138d2d   2 months ago     1.05GB
ytsaurus/ui                                     stable    0f15676a2557   3 months ago     1.25GB
ytsaurus/local                                  stable    b6d0a20fc2f0   3 months ago     794MB
postgres                                        14.2      9dbc24674f25   13 months ago    376MB
docker.elastic.co/elasticsearch/elasticsearch   7.16.2    66c29cde15ce   18 months ago    646MB
redis                                           5.0.9     987b553c835f   2 years ago      98.3MB
```
I can't find the image of yt.backend. is there any error in dockerfile?

**Comment by savnadya** [comment]
`ytsaurus/local:stable` - image for yt.backend

**Comment by dawsongzhao** [comment]
@savnadya Thanks. There is the logs.
```shell
docker logs f2a055837ab733bfd72dec10e96da3d2abaeacfbb1272f77ab050ce038c6c572
2023-06-23 12:39:39,208 INFO Start preparing cluster instance as follows:
2023-06-23 12:39:39,208 INFO   masters              1 (0 nonvoting) (version: 23.1.0-local-ya~0000000000000000+nobody)
2023-06-23 12:39:39,208 INFO   nodes                1 (0 chaos)     (version: 23.1.0-local-ya~0000000000000000+nobody)
2023-06-23 12:39:39,209 INFO   schedulers           1               (version: 23.1.0-local-ya~0000000000000000+nobody)
2023-06-23 12:39:39,209 INFO   controller agents    1               (version: 23.1.0-local-ya~0000000000000000+nobody)
2023-06-23 12:39:39,209 INFO   HTTP proxies         1               (version: 23.1.0-local-ya~0000000000000000+nobody)
2023-06-23 12:39:39,209 INFO   working dir          /tmp/98a69d5c-c50ce47f-48f2aadf-2aae424e
2023-06-23 12:39:39,209 INFO Preparing directories
2023-06-23 12:39:39,213 INFO Preparing configs
2023-06-23 12:39:39,273 INFO Finished preparing cluster instance
2023-06-23 12:39:39,274 INFO Starting http_proxy
2023-06-23 12:39:39,276 INFO Process http_proxy started (pid: 38, current_process_pid: 7)
2023-06-23 12:39:39,278 INFO Starting master
2023-06-23 12:39:39,282 INFO Process master started (pid: 39, current_process_pid: 7)
2023-06-23 12:39:39,282 INFO Waiting for http_proxy...
Http_proxy-0 stderr:
*** Aborted at 1687523979 (Unix time); Try "date -d @1687523979" if you are using GNU date ***
0x0000094d56ff in ??? at ???:0
*** SIGILL (Illegal instruction) (@0x94d5700) received by PID 38 (FID 0x0 TID 0x7f72115d5700) from PID 156063488 code ILL_ILLOPN (Illegal operand.) ***

ERR no page found read kernel-mode access
TRAPNO X86_TRAP_UD (Invalid Opcode)
R8 0x7f72115b4b78
R9 0x264a8072fd8
R10 0x7f72115b5940
R11 0x0
R12 0x0
R13 0x443b3f960550
R14 0x264a8072fd8
R15 0x7f72115b4cf0
RDI 0x443b3fcaaa00
RSI 0x1
RBP 0x7f72115b4ce8
RBX 0x443b3fc1f000
RDX 0x443b3fc4d3c0
RAX 0x94d5700
RCX 0x443b3fc83408
RSP 0x7f72115b4b58
RIP 0x94d5700
EFL 0x10206
CSGSFS 0x2b000000000033
OLDMASK 0x0
CR2 0x0 1. 0x00000bef9220 in ??? at ???:0
 2. 0x7f721646d08f in ??? at ???:0
*** Marked memory regions of total size 0 MB as undumpable ***
*** Waiting for logger to shut down ***
*** Terminating ***
2023-06-23 12:39:40,809 ERROR Failed to start environment
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/yt/environment/yt_env.py", line 494, in start
    self.synchronize()
  File "/usr/local/lib/python3.8/dist-packages/yt/environment/yt_env.py", line 589, in synchronize
    func()
  File "/usr/local/lib/python3.8/dist-packages/yt/environment/yt_env.py", line 1793, in <lambda>
    self._wait_or_skip(lambda: self._wait_for(proxy_ready, "http_proxy", max_wait_time=20), sync)
  File "/usr/local/lib/python3.8/dist-packages/yt/environment/yt_env.py", line 1904, in _wait_for
    result = condition()
  File "/usr/local/lib/python3.8/dist-packages/yt/environment/yt_env.py", line 1781, in proxy_ready
    self._validate_processes_are_running("http_proxy")
  File "/usr/local/lib/python3.8/dist-packages/yt/environment/yt_env.py", line 1897, in _validate_processes_are_running
    self._validate_process_is_running(process, name, index)
  File "/usr/local/lib/python3.8/dist-packages/yt/environment/yt_env.py", line 1889, in _validate_process_is_running
    raise YtError("Process {0} unexpectedly terminated with error code {1}. "
yt.common.YtError: Process http_proxy-0 unexpectedly terminated with error code -4. If the problem is reproducible please report to yt@yandex-team.ru mailing list.

***** Details:
Process http_proxy-0 unexpectedly terminated with error code -4. If the problem is reproducible please report to yt@yandex-team.ru mailing list.
    origin          f2a055837ab7 on 2023-06-23T12:39:40.809841Z

2023-06-23 12:39:40,810 INFO Killing watcher
2023-06-23 12:39:40,810 INFO Killing http_proxy
2023-06-23 12:39:40,810 INFO Killing node
2023-06-23 12:39:40,810 INFO Killing scheduler
2023-06-23 12:39:40,810 INFO Killing controller_agent
2023-06-23 12:39:40,810 INFO Killing master
2023-06-23 12:39:40,811 INFO Sending SIGTERM (pid: 39, current_process_pid: 7)
2023-06-23 12:39:40,911 INFO Killing driver
2023-06-23 12:39:40,911 INFO Killing driver_logging
Failed to start environment
    Process http_proxy-0 unexpectedly terminated with error code -4. If the problem is reproducible please report to yt@yandex-team.ru mailing list.

***** Details:
Failed to start environment
    origin          f2a055837ab7 on 2023-06-23T12:39:40.911720Z
Process http_proxy-0 unexpectedly terminated with error code -4. If the problem is reproducible please report to yt@yandex-team.ru mailing list.
    origin          f2a055837ab7 on 2023-06-23T12:39:40.809841Z
```

**Comment by dawsongzhao** [comment]
I run it by command,like this 
```shell
docker run -it --network yt_local_cluster_network  --name yt.backend  -p 8000:80  -p 8002:8002  \
    ytsaurus/local:stable \
    --fqdn "{'':-localhost}" \
    --proxy-config "{address_resolver={enable_ipv4=%true;enable_ipv6=%false;};coordinator={public_fqdn=\"localhost:8000\"}}" \
    --rpc-proxy-count 0 \
    --rpc-proxy-port 8002
```

**Comment by langchao209** [comment]
same issue for me 
`
2023-06-29 03:03:44,641 INFO Start preparing cluster instance as follows:
2023-06-29 03:03:44,641 INFO   masters              1 (0 nonvoting) (version: 23.1.0-local-ya~0000000000000000+nobody)
2023-06-29 03:03:44,641 INFO   nodes                1 (0 chaos)     (version: 23.1.0-local-ya~0000000000000000+nobody)
2023-06-29 03:03:44,641 INFO   schedulers           1               (version: 23.1.0-local-ya~0000000000000000+nobody)
2023-06-29 03:03:44,641 INFO   controller agents    1               (version: 23.1.0-local-ya~0000000000000000+nobody)
2023-06-29 03:03:44,641 INFO   HTTP proxies         1               (version: 23.1.0-local-ya~0000000000000000+nobody)
2023-06-29 03:03:44,641 INFO   working dir          /tmp/83cc60f7-d7de0466-5deda2ce-d5e362d6
2023-06-29 03:03:44,641 INFO Preparing directories
2023-06-29 03:03:44,642 INFO Preparing configs
2023-06-29 03:03:44,682 INFO Finished preparing cluster instance
2023-06-29 03:03:44,683 INFO Starting http_proxy
2023-06-29 03:03:44,686 INFO Process http_proxy started (pid: 40, current_process_pid: 9)
2023-06-29 03:03:44,687 INFO Starting master
2023-06-29 03:03:44,690 INFO Process master started (pid: 41, current_process_pid: 9)
2023-06-29 03:03:44,690 INFO Waiting for http_proxy...
2023-06-29 03:03:55,021 INFO Http_proxy ready
2023-06-29 03:03:55,022 INFO Waiting for master...
Master-0 stderr:
2023-06-29 03:03:44,920024	E	Build	Error parsing build time\n/home/nadya73/piglet_git/build/util/parser.rl6.cpp:9785: error in datetime parsing. Input data: \n    origin          172.17.17.41 (pid 41, tid ac1e787ed613f185, fid fffef51395318e67)\n    datetime        2023-06-29T03:03:44.920024Z\n	Control	fffef51395318e67
2023-06-29 03:03:45,173951	E	Master	World initialization failed\nService is unable to complete your request\n    code            105\n    origin          172.17.17.41 (pid 41, tid 25a59c459e332a1e, fid 0)\n    datetime        2023-06-29T03:03:45.172879Z\n    local           true\n    request_id      a99142f2-cbd99b4d-4824e7e5-bdfd3ef8\n	Automaton	fffef5138cd74351	2553d73-bb387f2-395c76c4-a4be2c38
2023-06-29 03:04:31,749 ERROR Failed to start environment
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/yt/environment/yt_env.py", line 494, in start
    self.synchronize()
  File "/usr/local/lib/python3.8/dist-packages/yt/environment/yt_env.py", line 589, in synchronize
    func()
  File "/usr/local/lib/python3.8/dist-packages/yt/environment/yt_env.py", line 1145, in <lambda>
    self._wait_or_skip(lambda: self._wait_for(cell_ready, master_name, max_wait_time=30), sync)
  File "/usr/local/lib/python3.8/dist-packages/yt/environment/yt_env.py", line 1925, in _wait_for
    raise error
yt.common.YtError: Master still not ready after 30 seconds. See logs in working dir for details.
    HTTPConnectionPool(host='172.17.17.41', port=80): Max retries exceeded with url: /api/v4 (Caused by NewConnectionError('<yt.packages.urllib3.connection.HTTPConnection object at 0x7f082b34e280>: Failed to establish a new connection: [Errno 111] Connection refused'))

***** Details:
Master still not ready after 30 seconds. See logs in working dir for details.
    origin          0d7e322f6b18 on 2023-06-29T03:04:31.749056Z
HTTPConnectionPool(host='172.17.17.41', port=80): Max retries exceeded with url: /api/v4 (Caused by NewConnectionError('<yt.packages.urllib3.connection.HTTPConnection object at 0x7f082b34e280>: Failed to establish a new connection: [Errno 111] Connection refused'))

2023-06-29 03:04:31,750 INFO Killing watcher

�
2023-06-29 03:04:31,750 INFO Killing http_proxy
2023-06-29 03:04:31,750 INFO Sending SIGTERM (pid: 40, current_process_pid: 9)
2023-06-29 03:04:31,851 INFO Killing node
2023-06-29 03:04:31,851 INFO Killing scheduler
2023-06-29 03:04:31,852 INFO Killing controller_agent
2023-06-29 03:04:31,852 INFO Killing master
2023-06-29 03:04:31,852 INFO Sending SIGTERM (pid: 41, current_process_pid: 9)
2023-06-29 03:04:31,953 INFO Killing driver
2023-06-29 03:04:31,953 INFO Killing driver_logging
Failed to start environment
    Master still not ready after 30 seconds. See logs in working dir for details.
        HTTPConnectionPool(host='172.17.17.41', port=80): Max retries exceeded with url: /api/v4 (Caused by NewConnectionError('<yt.packages.urllib3.connection.HTTPConnection object at 0x7f082b34e280>: Failed to establish a new connection: [Errno 111] Connection refused'))

***** Details:
Failed to start environment
    origin          0d7e322f6b18 on 2023-06-29T03:04:31.954544Z
Master still not ready after 30 seconds. See logs in working dir for details.
    origin          0d7e322f6b18 on 2023-06-29T03:04:31.749056Z
HTTPConnectionPool(host='172.17.17.41', port=80): Max retries exceeded with url: /api/v4 (Caused by NewConnectionError('<yt.packages.urllib3.connection.HTTPConnection object at 0x7f082b34e280>: Failed to establish a new connection: [Errno 111] Connection refused'))`

**Comment by savnadya** [comment]
@dawsongzhao @langchao209
Can you please try to run local YTsaurus with a different docker image:
`./run_local_cluster.sh --yt-version stable-debug`
And then send me logs.

**Comment by dawsongzhao0523** [comment]
@savnadya the error is same
```shell
2023-07-09 08:25:58 2023-07-09 00:25:58,329 INFO Start preparing cluster instance as follows:
2023-07-09 08:25:58 2023-07-09 00:25:58,329 INFO   masters              1 (0 nonvoting) (version: 23.1.0-local-yadebug~e9fea5defa71823d+nadya73)
2023-07-09 08:25:58 2023-07-09 00:25:58,329 INFO   nodes                1 (0 chaos)     (version: 23.1.0-local-yadebug~e9fea5defa71823d+nadya73)
2023-07-09 08:25:58 2023-07-09 00:25:58,329 INFO   schedulers           1               (version: 23.1.0-local-yadebug~e9fea5defa71823d+nadya73)
2023-07-09 08:25:58 2023-07-09 00:25:58,329 INFO   controller agents    1               (version: 23.1.0-local-yadebug~e9fea5defa71823d+nadya73)
2023-07-09 08:25:58 2023-07-09 00:25:58,329 INFO   HTTP proxies         1               (version: 23.1.0-local-yadebug~e9fea5defa71823d+nadya73)
2023-07-09 08:25:58 2023-07-09 00:25:58,329 INFO   working dir          /tmp/a4d33da0-1a820a03-b6a4deea-9d847cb1
2023-07-09 08:25:58 2023-07-09 00:25:58,329 INFO Preparing directories
2023-07-09 08:25:58 2023-07-09 00:25:58,331 INFO Preparing configs
2023-07-09 08:25:58 2023-07-09 00:25:58,376 INFO Finished preparing cluster instance
2023-07-09 08:25:58 2023-07-09 00:25:58,377 INFO Starting http_proxy
2023-07-09 08:25:58 2023-07-09 00:25:58,381 INFO Process http_proxy started (pid: 38, current_process_pid: 7)
2023-07-09 08:25:58 2023-07-09 00:25:58,382 INFO Starting master
2023-07-09 08:25:58 2023-07-09 00:25:58,390 INFO Process master started (pid: 39, current_process_pid: 7)
2023-07-09 08:25:58 2023-07-09 00:25:58,391 INFO Waiting for http_proxy...
2023-07-09 08:26:06 Http_proxy-0 stderr:
2023-07-09 08:26:06 *** Aborted at 1688862358 (Unix time); Try "date -d @1688862358" if you are using GNU date ***
2023-07-09 08:26:06 0x000020e12953 in NYT::NProfiling::TTscp::Get() at /home/nadya73/arc3/arcadia/yt/yt/core/profiling/tscp-inl.h:13
2023-07-09 08:26:06 *** SIGILL (Illegal instruction) (@0x20e12954) received by PID 38 (FID 0x0 TID 0x7fc435749540) from PID 551627092 code ILL_ILLOPN (Illegal operand.) ***
2023-07-09 08:26:06 
2023-07-09 08:26:06 ERR no page found read kernel-mode access
2023-07-09 08:26:06 TRAPNO X86_TRAP_UD (Invalid Opcode)
2023-07-09 08:26:06 R8 0x7ffe326d8348
2023-07-09 08:26:06 R9 0x88b53ab3f46
2023-07-09 08:26:06 R10 0x5
2023-07-09 08:26:06 R11 0x0
2023-07-09 08:26:06 R12 0x1febc000
2023-07-09 08:26:06 R13 0x7ffe326d9c30
2023-07-09 08:26:06 R14 0x0
2023-07-09 08:26:06 R15 0x0
2023-07-09 08:26:06 RDI 0x16b8bfcaea00
2023-07-09 08:26:06 RSI 0x1
2023-07-09 08:26:06 RBP 0x7ffe326d8210
2023-07-09 08:26:06 RBX 0x3288c220
2023-07-09 08:26:06 RDX 0x5
2023-07-09 08:26:06 RAX 0x16b8bfcaea00
2023-07-09 08:26:06 RCX 0x16b8bfc7e470
2023-07-09 08:26:06 RSP 0x7ffe326d8210
2023-07-09 08:26:06 RIP 0x20e12954
2023-07-09 08:26:06 EFL 0x10202
2023-07-09 08:26:06 CSGSFS 0x2b000000000033
2023-07-09 08:26:06 OLDMASK 0x0
2023-07-09 08:26:06 CR2 0x0 1. 0x000020be9d1d in NYT::CrashSignalHandler(int, siginfo_t*, void*) at /home/nadya73/arc3/arcadia/yt/yt/core/misc/crash_handler.cpp:499
2023-07-09 08:26:06  2. 0x00001fffba64 in decltype(static_cast<void (*&>(fp)(static_cast<int>(fp0), static_cast<siginfo_t*>(fp0), static_cast<void*>(fp0))) std::__y1::__invoke<void (*&)(int, siginfo_t*, void*), int, siginfo_t*, void*>(void (*&)(int, siginfo_t*, void*), int&&, siginfo_t*&&, void*&&) at /home/nadya73/arc3/arcadia/contrib/libs/cxxsupp/libcxx/include/type_traits:3663
2023-07-09 08:26:06  3. 0x00001fffb9fb in void std::__y1::__invoke_void_return_wrapper<void, true>::__call<void (*&)(int, siginfo_t*, void*), int, siginfo_t*, void*>(void (*&)(int, siginfo_t*, void*), int&&, siginfo_t*&&, void*&&) at /home/nadya73/arc3/arcadia/contrib/libs/cxxsupp/libcxx/include/__functional/invoke.h:61
2023-07-09 08:26:06  4. 0x00001fffb97b in std::__y1::__function::__alloc_func<void (*)(int, siginfo_t*, void*), std::__y1::allocator<void (*)(int, siginfo_t*, void*)>, void (int, siginfo_t*, void*)>::operator()(int&&, siginfo_t*&&, void*&&) at /home/nadya73/arc3/arcadia/contrib/libs/cxxsupp/libcxx/include/__functional/function.h:181
2023-07-09 08:26:06  5. 0x00001fffaa6a in std::__y1::__function::__func<void (*)(int, siginfo_t*, void*), std::__y1::allocator<void (*)(int, siginfo_t*, void*)>, void (int, siginfo_t*, void*)>::operator()(int&&, siginfo_t*&&, void*&&) at /home/nadya73/arc3/arcadia/contrib/libs/cxxsupp/libcxx/include/__functional/function.h:355
2023-07-09 08:26:06  6. 0x000020cd0a73 in std::__y1::__function::__value_func<void (int, siginfo_t*, void*)>::operator()(int&&, siginfo_t*&&, void*&&) const at /home/nadya73/arc3/arcadia/contrib/libs/cxxsupp/libcxx/include/__functional/function.h:508
2023-07-09 08:26:06  7. 0x000020cc9e75 in std::__y1::function<void (int, siginfo_t*, void*)>::operator()(int, siginfo_t*, void*) const at /home/nadya73/arc3/arcadia/contrib/libs/cxxsupp/libcxx/include/__functional/function.h:1192
2023-07-09 08:26:06  8. 0x000020cc9cd2 in NYT::TSignalRegistry::Handle(int, siginfo_t*, void*) at /home/nadya73/arc3/arcadia/yt/yt/core/misc/signal_registry.cpp:165
2023-07-09 08:26:06  9. 0x7fc435aa741f in ??? at ???:0
2023-07-09 08:26:06 10. 0x000020e12953 in NYT::NProfiling::TTscp::Get() at /home/nadya73/arc3/arcadia/yt/yt/core/profiling/tscp-inl.h:13
2023-07-09 08:26:06 11. 0x0000221ecbec in NYT::NProfiling::TPerCpuCounter::Increment(long) at /home/nadya73/arc3/arcadia/yt/yt/library/profiling/solomon/percpu.cpp:12
2023-07-09 08:26:06 12. 0x0000208de8af in NYT::NProfiling::TCounter::Increment(long) const at /home/nadya73/arc3/arcadia/yt/yt/library/profiling/sensor.cpp:22
2023-07-09 08:26:06 13. 0x000020a26cb5 in NYT::NConcurrency::TInvokerQueue<NYT::NConcurrency::TMpscQueueImpl>::EnqueueCallback(NYT::TCallback<void ()>, int, NYT::TIntrusivePtr<NYT::NYTProf::TProfilerTag>)::'lambda'(std::__y1::unique_ptr<NYT::NConcurrency::TInvokerQueue<NYT::NConcurrency::TMpscQueueImpl>::TCounters, std::__y1::default_delete<NYT::NConcurrency::TInvokerQueue<NYT::NConcurrency::TMpscQueueImpl>::TCounters> > const&)::operator()(std::__y1::unique_ptr<NYT::NConcurrency::TInvokerQueue<NYT::NConcurrency::TMpscQueueImpl>::TCounters, std::__y1::default_delete<NYT::NConcurrency::TInvokerQueue<NYT::NConcurrency::TMpscQueueImpl>::TCounters> > const&) const at /home/nadya73/arc3/arcadia/yt/yt/core/concurrency/invoker_queue.cpp:384
2023-07-09 08:26:06 14. 0x000020a2614a in NYT::NConcurrency::TInvokerQueue<NYT::NConcurrency::TMpscQueueImpl>::EnqueueCallback(NYT::TCallback<void ()>, int, NYT::TIntrusivePtr<NYT::NYTProf::TProfilerTag>) at /home/nadya73/arc3/arcadia/yt/yt/core/concurrency/invoker_queue.cpp:387
2023-07-09 08:26:06 15. 0x000020a255c5 in NYT::NConcurrency::TInvokerQueue<NYT::NConcurrency::TMpscQueueImpl>::Invoke(NYT::TCallback<void ()>, int, NYT::TIntrusivePtr<NYT::NYTProf::TProfilerTag>) at /home/nadya73/arc3/arcadia/yt/yt/core/concurrency/invoker_queue.cpp:336
2023-07-09 08:26:06 16. 0x000020a254f6 in NYT::NConcurrency::TInvokerQueue<NYT::NConcurrency::TMpscQueueImpl>::Invoke(NYT::TCallback<void ()>) at /home/nadya73/arc3/arcadia/yt/yt/core/concurrency/invoker_queue.cpp:320
2023-07-09 08:26:06 17. 0x0000208f9328 in NYT::GuardedInvoke(NYT::TIntrusivePtr<NYT::IInvoker> const&, NYT::TCallback<void ()>, NYT::TCallback<void ()>) at /home/nadya73/arc3/arcadia/yt/yt/core/actions/invoker_util.cpp:181
2023-07-09 08:26:06 18. 0x000020a3d94f in NYT::NConcurrency::TPeriodicExecutor::PostCallback() at /home/nadya73/arc3/arcadia/yt/yt/core/concurrency/periodic_executor.cpp:160
2023-07-09 08:26:06 19. 0x000020a3d807 in NYT::NConcurrency::TPeriodicExecutor::ScheduleOutOfBand() at /home/nadya73/arc3/arcadia/yt/yt/core/concurrency/periodic_executor.cpp:143
2023-07-09 08:26:06 20. 0x000020b55753 in NYT::NLogging::TLogManager::TImpl::Configure(NYT::TIntrusivePtr<NYT::NLogging::TLogManagerConfig>, bool, bool) at /home/nadya73/arc3/arcadia/yt/yt/core/logging/log_manager.cpp:457
2023-07-09 08:26:06 21. 0x000020b55456 in NYT::NLogging::TLogManager::Configure(NYT::TIntrusivePtr<NYT::NLogging::TLogManagerConfig>, bool) at /home/nadya73/arc3/arcadia/yt/yt/core/logging/log_manager.cpp:1470
2023-07-09 08:26:06 22. 0x000022491833 in void NYT::ConfigureSingletonsImpl<NYT::TIntrusivePtr<NYT::TSingletonsConfig> >(NYT::TIntrusivePtr<NYT::TSingletonsConfig> const&) at /home/nadya73/arc3/arcadia/yt/yt/library/program/helpers.cpp:193
2023-07-09 08:26:06 23. 0x000022491694 in NYT::ConfigureSingletons(NYT::TIntrusivePtr<NYT::TSingletonsConfig> const&) at /home/nadya73/arc3/arcadia/yt/yt/library/program/helpers.cpp:238
2023-07-09 08:26:06 24. 0x000028183f75 in NYT::ConfigureNativeSingletons(NYT::TIntrusivePtr<NYT::TNativeSingletonsConfig> const&) at /home/nadya73/arc3/arcadia/yt/yt/ytlib/program/helpers.cpp:15
2023-07-09 08:26:06 25. 0x0000200e79b0 in NYT::NHttpProxy::THttpProxyProgram::DoRun(NLastGetopt::TOptsParseResult const&) at /home/nadya73/arc3/arcadia/yt/yt/server/http_proxy/program.h:113
2023-07-09 08:26:06 26. 0x0000226f185d in NYT::TProgram::Run(int, char const**)::$_0::operator()() const at /home/nadya73/arc3/arcadia/yt/yt/library/program/program.cpp:134
2023-07-09 08:26:06 27. 0x0000226f1721 in NYT::TProgram::Run(int, char const**) at /home/nadya73/arc3/arcadia/yt/yt/library/program/program.cpp:139
2023-07-09 08:26:06 28. 0x000020057134 in void TryProgram<NYT::NHttpProxy::THttpProxyProgram>(int, char const**, TBasicString<char, std::__y1::char_traits<char> > const&) at /home/nadya73/arc3/arcadia/yt/yt/server/all/main.cpp:44
2023-07-09 08:26:06 29. 0x00002005668a in main at /home/nadya73/arc3/arcadia/yt/yt/server/all/main.cpp:52
2023-07-09 08:26:06 30. 0x7fc4358c0082 in ??? at ???:0
2023-07-09 08:26:06 31. 0x00001febc028 in ??? at ???:0
2023-07-09 08:26:06 *** Marked memory regions of total size 0 MB as undumpable ***
2023-07-09 08:26:06 *** Waiting for logger to shut down ***
2023-07-09 08:26:06 *** Terminating ***
2023-07-09 08:26:06 2023-07-09 00:26:06,875 ERROR Failed to start environment
2023-07-09 08:26:06 Traceback (most recent call last):
2023-07-09 08:26:06   File "/usr/local/lib/python3.8/dist-packages/yt/environment/yt_env.py", line 494, in start
2023-07-09 08:26:06     self.synchronize()
2023-07-09 08:26:06   File "/usr/local/lib/python3.8/dist-packages/yt/environment/yt_env.py", line 589, in synchronize
2023-07-09 08:26:06     func()
2023-07-09 08:26:06   File "/usr/local/lib/python3.8/dist-packages/yt/environment/yt_env.py", line 1793, in <lambda>
2023-07-09 08:26:06     self._wait_or_skip(lambda: self._wait_for(proxy_ready, "http_proxy", max_wait_time=20), sync)
2023-07-09 08:26:06   File "/usr/local/lib/python3.8/dist-packages/yt/environment/yt_env.py", line 1904, in _wait_for
2023-07-09 08:26:06     result = condition()
2023-07-09 08:26:06   File "/usr/local/lib/python3.8/dist-packages/yt/environment/yt_env.py", line 1781, in proxy_ready
2023-07-09 08:26:06     self._validate_processes_are_running("http_proxy")
2023-07-09 08:26:06   File "/usr/local/lib/python3.8/dist-packages/yt/environment/yt_env.py", line 1897, in _validate_processes_are_running
2023-07-09 08:26:06     self._validate_process_is_running(process, name, index)
2023-07-09 08:26:06   File "/usr/local/lib/python3.8/dist-packages/yt/environment/yt_env.py", line 1889, in _validate_process_is_running
2023-07-09 08:26:06     raise YtError("Process {0} unexpectedly terminated with error code {1}. "
2023-07-09 08:26:06 yt.common.YtError: Process http_proxy-0 unexpectedly terminated with error code -4. If the problem is reproducible please report to yt@yandex-team.ru mailing list.
2023-07-09 08:26:06 
2023-07-09 08:26:06 ***** Details:
2023-07-09 08:26:06 Process http_proxy-0 unexpectedly terminated with error code -4. If the problem is reproducible please report to yt@yandex-team.ru mailing list.    
2023-07-09 08:26:06     origin          9b09946c01d2 on 2023-07-09T00:26:06.875268Z
2023-07-09 08:26:06 
2023-07-09 08:26:06 2023-07-09 00:26:06,875 INFO Killing watcher
2023-07-09 08:26:06 2023-07-09 00:26:06,875 INFO Killing http_proxy
2023-07-09 08:26:06 2023-07-09 00:26:06,875 INFO Killing node
2023-07-09 08:26:06 2023-07-09 00:26:06,875 INFO Killing scheduler
2023-07-09 08:26:06 2023-07-09 00:26:06,875 INFO Killing controller_agent
2023-07-09 08:26:06 2023-07-09 00:26:06,875 INFO Killing master
2023-07-09 08:26:06 2023-07-09 00:26:06,876 INFO Killing driver
2023-07-09 08:26:06 2023-07-09 00:26:06,876 INFO Killing driver_logging
2023-07-09 08:26:06 Failed to start environment
2023-07-09 08:26:06     Process http_proxy-0 unexpectedly terminated with error code -4. If the problem is reproducible please report to yt@yandex-team.ru mailing list.
2023-07-09 08:26:06 
2023-07-09 08:26:06 ***** Details:
2023-07-09 08:26:06 Failed to start environment    
2023-07-09 08:26:06     origin          9b09946c01d2 on 2023-07-09T00:26:06.876163Z
2023-07-09 08:26:06 Process http_proxy-0 unexpectedly terminated with error code -4. If the problem is reproducible please report to yt@yandex-team.ru mailing list.    
2023-07-09 08:26:06     origin          9b09946c01d2 on 2023-07-09T00:26:06.875268Z
2023-07-09 08:26:06 

```

**Comment by gritukan** [comment]
Hi!

Seems like your processor does not support rdtscp instruction. Tried to fix it with 5fb129d6863666b861879bac80f5ddefc1e856fe. Can you please try last nightly image to check if everything works fine?

**Comment by dawsongzhao0523** [comment]
@gritukan how to get the last nightly image?I use this it error.

./run_local_cluster.sh --yt-version nightly
Error response from daemon: manifest for ytsaurus/local:nightly not found: manifest unknown: manifest unknown

**Comment by savnadya** [comment]
`ytsaurus/local:dev` - try this

**Comment by dawsongzhao0523** [comment]
@savnadya 
`ytsaurus/local:dev` it's work. i love it . thank you.
<img width="2022" alt="image" src="https://github.com/ytsaurus/ytsaurus/assets/133857587/6611fc4a-a7d0-4387-a80e-6bcf427ee176">
