### ISSUE TITLE
Example fails on CRI Exec node

### ISSUE THREAD

**Issue by spiner2000** [ytsaurus/ytsaurus#647]
https://github.com/ytsaurus/ytsaurus/blob/main/yt/python/examples/spec_builder_typed/example.py

Error:

```
Traceback (most recent call last):
  File "/slot/sandbox/_py_runner.py", line 174, in <module>
    main()
  File "/slot/sandbox/_py_runner.py", line 170, in main
    yt.wrapper.py_runner_helpers.process_rows(__operation_dump_filename, __config_dump_filename, start_time=start_time)
  File "/slot/sandbox/./tmpfs/modules/yt/wrapper/py_runner_helpers.py", line 416, in process_rows
    params.output_format.dump_rows(result, output_streams, raw=raw)
  File "/slot/sandbox/./tmpfs/modules/yt/wrapper/format.py", line 303, in dump_rows
    self._dump_rows(rows, stream_or_streams)
  File "/slot/sandbox/./tmpfs/modules/yt/wrapper/format.py", line 422, in _dump_rows
    skiff.dump_structured(rows, streams, self._py_schemas, self._skiff_schemas_prepared)
  File "/slot/sandbox/./tmpfs/modules/yt/wrapper/skiff.py", line 46, in dump_structured
    print(args)
  File "/slot/sandbox/./tmpfs/modules/yt/wrapper/py_runner_helpers.py", line 30, in __getattr__
    raise YtStandardStreamAccessError("Stdin, stdout are inaccessible for Python operations"
yt.wrapper.py_runner_helpers.YtStandardStreamAccessError: Stdin, stdout are inaccessible for Python operations without raw_io attribute

***** Details:
Stdin, stdout are inaccessible for Python operations without raw_io attribute    
    origin          end-large-0.exec-nodes-large.ytsaurus.svc.cluster.local on 2024-06-08T14:57:21.505948Z
```

base python 3.11 image was used for job with 

pip install pandas \
    requests \
    ytsaurus-yson ytsaurus-client \
    lxml \
    xmlschema \
    requests \
    xmltodict

The operations are working fine without explicit types.

**Comment by denvr** [comment]
Direct access to stdout is forbidden inside operations.
It seems to be local debug print inside skiff.py?
```
...
  File "/slot/sandbox/./tmpfs/modules/yt/wrapper/skiff.py", line 46, in dump_structured
    print(args)
...
```

**Comment by spiner2000** [comment]
@denvr Yes, you are right. I was debugging some issues a while ago, and forgot to revert my changes and they were pickled. Thanks a lot!
