### ISSUE TITLE
Spyt decimals do not work when written using python encode_decimal

### ISSUE THREAD

**Issue by Hattonuri** [ytsaurus/ytsaurus#88]
23/08/29 11:04:40 WARN TaskSetManager: Lost task 0.0 in stage 4.0 (TID 10) (end-3.exec-nodes.default.svc.cluster.local executor 6): java.lang.ClassCastException: class org.apache.spark.unsafe.types.UTF8String cannot be cast to class org.apache.spark.sql.types.Decimal (org.apache.spark.unsafe.types.UTF8String and org.apache.spark.sql.types.Decimal are in unnamed module of loader 'app')
  at org.apache.spark.sql.catalyst.util.GenericArrayData.getDecimal(GenericArrayData.scala:72)
  at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
  at org.apache.spark.sql.v2.YtPartitionReaderFactory$$anon$3.nextKeyValue(YtPartitionReaderFactory.scala:179)
  at org.apache.spark.sql.v2.YtPartitionReaderFactory$$anon$1.next(YtPartitionReaderFactory.scala:88)
  at org.apache.spark.sql.execution.datasources.v2.PartitionReaderWithPartitionValues.next(PartitionReaderWithPartitionValues.scala:48)
  at org.apache.spark.sql.execution.datasources.v2.PartitionedFileReader.next(FilePartitionReaderFactory.scala:55)
  at org.apache.spark.sql.execution.datasources.v2.FilePartitionReader.next(FilePartitionReader.scala:64)

**Comment by alextokarew** [comment]
Support for Decimal serialization/deserialization was added not so long ago by this commit: https://github.com/ytsaurus/ytsaurus/commit/8b1c674f89073769f5154c8ba7e43b940216700b

Try to upgrade to 1.71.0 version of spyt.

**Comment by Hattonuri** [comment]
Tried - did not work :(

**Comment by alextokarew** [comment]
Is this issue still actual? I think it has the same origin as https://github.com/ytsaurus/ytsaurus/issues/58
